@echo off
setlocal EnableExtensions DisableDelayedExpansion
title Codex Uninstaller
rem Single-file launcher.
rem The long Base64 lines below are the embedded PowerShell uninstaller script.
rem This keeps Korean/English UI text reliable on Windows while users download only this .bat.
rem It decodes to %TEMP%, runs, then deletes the temporary files.
set "TMP_PS=%TEMP%\codex-uninstaller-%RANDOM%%RANDOM%.ps1"
set "TMP_B64=%TEMP%\codex-uninstaller-%RANDOM%%RANDOM%.b64"
break > "%TMP_B64%"
>> "%TMP_B64%" echo 77u/JEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJDb250aW51ZSIKCiRMb2dGaWxlID0gSm9pbi1Q
>> "%TMP_B64%" echo YXRoICRlbnY6VEVNUCAoImNvZGV4LXVuaW5zdGFsbC17MH0ubG9nIiAtZiAoW0d1aWRdOjpOZXdH
>> "%TMP_B64%" echo dWlkKCkuVG9TdHJpbmcoIk4iKS5TdWJzdHJpbmcoMCwgOCkpKQoKZnVuY3Rpb24gV3JpdGUtQmkg
>> "%TMP_B64%" echo ewogICAgcGFyYW0oCiAgICAgICAgW1BhcmFtZXRlcihNYW5kYXRvcnkgPSAkdHJ1ZSldW3N0cmlu
>> "%TMP_B64%" echo Z10kS28sCiAgICAgICAgW1BhcmFtZXRlcihNYW5kYXRvcnkgPSAkdHJ1ZSldW3N0cmluZ10kRW4K
>> "%TMP_B64%" echo ICAgICkKICAgIFdyaXRlLUhvc3QgJEtvCiAgICBXcml0ZS1Ib3N0ICRFbgp9CgpmdW5jdGlvbiBB
>> "%TMP_B64%" echo ZGQtTG9nIHsKICAgIHBhcmFtKFtzdHJpbmddJE1lc3NhZ2UpCiAgICBBZGQtQ29udGVudCAtTGl0
>> "%TMP_B64%" echo ZXJhbFBhdGggJExvZ0ZpbGUgLVZhbHVlICRNZXNzYWdlIC1FbmNvZGluZyBVVEY4Cn0KCmZ1bmN0
>> "%TMP_B64%" echo aW9uIFRlc3QtQWRtaW4gewogICAgJGlkZW50aXR5ID0gW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5k
>> "%TMP_B64%" echo b3dzSWRlbnRpdHldOjpHZXRDdXJyZW50KCkKICAgICRwcmluY2lwYWwgPSBOZXctT2JqZWN0IFNl
>> "%TMP_B64%" echo Y3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsKCRpZGVudGl0eSkKICAgIHJldHVybiAk
>> "%TMP_B64%" echo cHJpbmNpcGFsLklzSW5Sb2xlKFtTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0J1aWx0SW5Sb2xl
>> "%TMP_B64%" echo XTo6QWRtaW5pc3RyYXRvcikKfQoKZnVuY3Rpb24gVGVzdC1Db2RleFRhcmdldCB7CiAgICBwYXJh
>> "%TMP_B64%" echo bShbc3RyaW5nXSRQYXRoKQogICAgaWYgKFtzdHJpbmddOjpJc051bGxPcldoaXRlU3BhY2UoJFBh
>> "%TMP_B64%" echo dGgpKSB7CiAgICAgICAgcmV0dXJuICRmYWxzZQogICAgfQoKICAgICRub3JtYWxpemVkID0gJFBh
>> "%TMP_B64%" echo dGguVG9Mb3dlckludmFyaWFudCgpCiAgICByZXR1cm4gKAogICAgICAgICRub3JtYWxpemVkLkNv
>> "%TMP_B64%" echo bnRhaW5zKCJcLmNvZGV4IikgLW9yCiAgICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMoIlxjb2Rl
>> "%TMP_B64%" echo eCIpIC1vcgogICAgICAgICRub3JtYWxpemVkLkNvbnRhaW5zKCJjb2RleC4iKSAtb3IKICAgICAg
>> "%TMP_B64%" echo ICAkbm9ybWFsaXplZC5Db250YWlucygiY29kZXgubG5rIikgLW9yCiAgICAgICAgJG5vcm1hbGl6
>> "%TMP_B64%" echo ZWQuQ29udGFpbnMoIm9wZW5haSBjb2RleCIpIC1vcgogICAgICAgICRub3JtYWxpemVkLkNvbnRh
>> "%TMP_B64%" echo aW5zKCJcb3BlbmFpXGNvZGV4IikgLW9yCiAgICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMoImNv
>> "%TMP_B64%" echo bS5vcGVuYWkuY29kZXgiKSAtb3IKICAgICAgICAkbm9ybWFsaXplZC5Db250YWlucygiXEBvcGVu
>> "%TMP_B64%" echo YWlcY29kZXgiKQogICAgKQp9CgpmdW5jdGlvbiBSZW1vdmUtQ29kZXhEaXJlY3RvcnkgewogICAg
>> "%TMP_B64%" echo cGFyYW0oW3N0cmluZ10kUGF0aCkKICAgIGlmIChbc3RyaW5nXTo6SXNOdWxsT3JXaGl0ZVNwYWNl
>> "%TMP_B64%" echo KCRQYXRoKSAtb3IgLW5vdCAoVGVzdC1QYXRoIC1MaXRlcmFsUGF0aCAkUGF0aCAtUGF0aFR5cGUg
>> "%TMP_B64%" echo Q29udGFpbmVyKSkgewogICAgICAgIHJldHVybgogICAgfQoKICAgIGlmICgtbm90IChUZXN0LUNv
>> "%TMP_B64%" echo ZGV4VGFyZ2V0IC1QYXRoICRQYXRoKSkgewogICAgICAgIFdyaXRlLUJpICLslYjsoIQg67KU7JyE
>> "%TMP_B64%" echo IOuwluydtOudvCDqsbTrhIjrnIA6ICRQYXRoIiAiU2tpcHBlZCB1bnNhZmUgZGlyZWN0b3J5OiAk
>> "%TMP_B64%" echo UGF0aCIKICAgICAgICBBZGQtTG9nICJTa2lwcGVkIHVuc2FmZSBkaXJlY3Rvcnk6ICRQYXRoIgog
>> "%TMP_B64%" echo ICAgICAgIHJldHVybgogICAgfQoKICAgIHRyeSB7CiAgICAgICAgUmVtb3ZlLUl0ZW0gLUxpdGVy
>> "%TMP_B64%" echo YWxQYXRoICRQYXRoIC1SZWN1cnNlIC1Gb3JjZSAtRXJyb3JBY3Rpb24gU3RvcAogICAgICAgIFdy
>> "%TMP_B64%" echo aXRlLUJpICLtj7TrjZQg7IKt7KCcIOyZhOujjDogJFBhdGgiICJSZW1vdmVkIGRpcmVjdG9yeTog
>> "%TMP_B64%" echo JFBhdGgiCiAgICAgICAgQWRkLUxvZyAiUmVtb3ZlZCBkaXJlY3Rvcnk6ICRQYXRoIgogICAgfSBj
>> "%TMP_B64%" echo YXRjaCB7CiAgICAgICAgV3JpdGUtQmkgIu2PtOuNlCDsgq3soJwg7Iuk7YyoOiAkUGF0aCIgIkZh
>> "%TMP_B64%" echo aWxlZCB0byByZW1vdmUgZGlyZWN0b3J5OiAkUGF0aCIKICAgICAgICBBZGQtTG9nICJGYWlsZWQg
>> "%TMP_B64%" echo dG8gcmVtb3ZlIGRpcmVjdG9yeTogJFBhdGggLSAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdlKSIKICAg
>> "%TMP_B64%" echo IH0KfQoKZnVuY3Rpb24gUmVtb3ZlLUNvZGV4RmlsZSB7CiAgICBwYXJhbShbc3RyaW5nXSRQYXRo
>> "%TMP_B64%" echo KQogICAgaWYgKFtzdHJpbmddOjpJc051bGxPcldoaXRlU3BhY2UoJFBhdGgpIC1vciAtbm90IChU
>> "%TMP_B64%" echo ZXN0LVBhdGggLUxpdGVyYWxQYXRoICRQYXRoIC1QYXRoVHlwZSBMZWFmKSkgewogICAgICAgIHJl
>> "%TMP_B64%" echo dHVybgogICAgfQoKICAgIGlmICgtbm90IChUZXN0LUNvZGV4VGFyZ2V0IC1QYXRoICRQYXRoKSkg
>> "%TMP_B64%" echo ewogICAgICAgIFdyaXRlLUJpICLslYjsoIQg67KU7JyEIOuwluydtOudvCDqsbTrhIjrnIA6ICRQ
>> "%TMP_B64%" echo YXRoIiAiU2tpcHBlZCB1bnNhZmUgZmlsZTogJFBhdGgiCiAgICAgICAgQWRkLUxvZyAiU2tpcHBl
>> "%TMP_B64%" echo ZCB1bnNhZmUgZmlsZTogJFBhdGgiCiAgICAgICAgcmV0dXJuCiAgICB9CgogICAgdHJ5IHsKICAg
>> "%TMP_B64%" echo ICAgICBSZW1vdmUtSXRlbSAtTGl0ZXJhbFBhdGggJFBhdGggLUZvcmNlIC1FcnJvckFjdGlvbiBT
>> "%TMP_B64%" echo dG9wCiAgICAgICAgV3JpdGUtQmkgIu2MjOydvCDsgq3soJwg7JmE66OMOiAkUGF0aCIgIlJlbW92
>> "%TMP_B64%" echo ZWQgZmlsZTogJFBhdGgiCiAgICAgICAgQWRkLUxvZyAiUmVtb3ZlZCBmaWxlOiAkUGF0aCIKICAg
>> "%TMP_B64%" echo IH0gY2F0Y2ggewogICAgICAgIFdyaXRlLUJpICLtjIzsnbwg7IKt7KCcIOyLpO2MqDogJFBhdGgi
>> "%TMP_B64%" echo ICJGYWlsZWQgdG8gcmVtb3ZlIGZpbGU6ICRQYXRoIgogICAgICAgIEFkZC1Mb2cgIkZhaWxlZCB0
>> "%TMP_B64%" echo byByZW1vdmUgZmlsZTogJFBhdGggLSAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdlKSIKICAgIH0KfQoK
>> "%TMP_B64%" echo ZnVuY3Rpb24gU3RvcC1Db2RleFByb2Nlc3NlcyB7CiAgICBXcml0ZS1CaSAi7Iuk7ZaJIOykkeyd
>> "%TMP_B64%" echo uCBDb2RleOulvCDsooXro4ztlanri4jri6QuLi4iICJDbG9zaW5nIENvZGV4IGlmIGl0IGlzIHJ1
>> "%TMP_B64%" echo bm5pbmcuLi4iCiAgICBBZGQtTG9nICJDbG9zaW5nIENvZGV4IHByb2Nlc3Nlcy4uLiIKCiAgICAk
>> "%TMP_B64%" echo cHJvY2Vzc05hbWVzID0gQCgiQ29kZXgiLCAiT3BlbkFJIENvZGV4IiwgImNvZGV4IikKICAgIGZv
>> "%TMP_B64%" echo cmVhY2ggKCRuYW1lIGluICRwcm9jZXNzTmFtZXMpIHsKICAgICAgICBHZXQtUHJvY2VzcyAtTmFt
>> "%TMP_B64%" echo ZSAkbmFtZSAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSB8IEZvckVhY2gtT2JqZWN0IHsK
>> "%TMP_B64%" echo ICAgICAgICAgICAgdHJ5IHsKICAgICAgICAgICAgICAgIFN0b3AtUHJvY2VzcyAtSWQgJF8uSWQg
>> "%TMP_B64%" echo LUZvcmNlIC1FcnJvckFjdGlvbiBTdG9wCiAgICAgICAgICAgICAgICBBZGQtTG9nICJTdG9wcGVk
>> "%TMP_B64%" echo IHByb2Nlc3M6ICQoJF8uUHJvY2Vzc05hbWUpIFskKCRfLklkKV0iCiAgICAgICAgICAgIH0gY2F0
>> "%TMP_B64%" echo Y2ggewogICAgICAgICAgICAgICAgQWRkLUxvZyAiRmFpbGVkIHRvIHN0b3AgcHJvY2VzczogJCgk
>> "%TMP_B64%" echo Xy5Qcm9jZXNzTmFtZSkgWyQoJF8uSWQpXSAtICQoJF8uRXhjZXB0aW9uLk1lc3NhZ2UpIgogICAg
>> "%TMP_B64%" echo ICAgICAgICB9CiAgICAgICAgfQogICAgfQp9CgpmdW5jdGlvbiBVbmluc3RhbGwtS25vd25QYWNr
>> "%TMP_B64%" echo YWdlcyB7CiAgICBXcml0ZS1CaSAi7JWM66Ck7KeEIENvZGV4IO2MqO2CpOyngCDshKTsuZgg7ZWt
>> "%TMP_B64%" echo 66qp7J2EIO2ZleyduO2VqeuLiOuLpC4uLiIgIkNoZWNraW5nIGtub3duIENvZGV4IHBhY2thZ2Ug
>> "%TMP_B64%" echo aW5zdGFsbGVycy4uLiIKICAgIEFkZC1Mb2cgIkNoZWNraW5nIHBhY2thZ2UgaW5zdGFsbGVycy4u
>> "%TMP_B64%" echo LiIKCiAgICBpZiAoR2V0LUNvbW1hbmQgd2luZ2V0IC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRp
>> "%TMP_B64%" echo bnVlKSB7CiAgICAgICAgJHdpbmdldElkcyA9IEAoIk9wZW5BSS5Db2RleCIsICJPcGVuQUkuQ29k
>> "%TMP_B64%" echo ZXhDTEkiLCAiQ29kZXguQ29kZXgiKQogICAgICAgIGZvcmVhY2ggKCRpZCBpbiAkd2luZ2V0SWRz
>> "%TMP_B64%" echo KSB7CiAgICAgICAgICAgIEFkZC1Mb2cgIndpbmdldCB1bmluc3RhbGwgLS1pZCAkaWQgLS1leGFj
>> "%TMP_B64%" echo dCIKICAgICAgICAgICAgJiB3aW5nZXQgdW5pbnN0YWxsIC0taWQgJGlkIC0tZXhhY3QgLS1zaWxl
>> "%TMP_B64%" echo bnQgLS1hY2NlcHQtc291cmNlLWFncmVlbWVudHMgLS1kaXNhYmxlLWludGVyYWN0aXZpdHkgKj4+
>> "%TMP_B64%" echo ICRMb2dGaWxlCiAgICAgICAgfQogICAgfQoKICAgIGlmIChHZXQtQ29tbWFuZCBucG0gLUVycm9y
>> "%TMP_B64%" echo QWN0aW9uIFNpbGVudGx5Q29udGludWUpIHsKICAgICAgICBBZGQtTG9nICJucG0gdW5pbnN0YWxs
>> "%TMP_B64%" echo IC1nIEBvcGVuYWkvY29kZXgiCiAgICAgICAgJiBucG0gdW5pbnN0YWxsIC1nICJAb3BlbmFpL2Nv
>> "%TMP_B64%" echo ZGV4IiAqPj4gJExvZ0ZpbGUKICAgIH0KfQoKZnVuY3Rpb24gUmVtb3ZlLUtub3duUGF0aHMgewog
>> "%TMP_B64%" echo ICAgV3JpdGUtQmkgIkNvZGV4IO2MjOydvCwg7Iqk7YKsLCDshKTsoJUsIOy6kOyLnCwg64yA7ZmU
>> "%TMP_B64%" echo IOq4sOuhneydhCDsgq3soJztlanri4jri6QuLi4iICJSZW1vdmluZyBDb2RleCBmaWxlcywgc2tp
>> "%TMP_B64%" echo bGxzLCBzZXR0aW5ncywgY2FjaGUsIGFuZCBjaGF0IGRhdGEuLi4iCiAgICBBZGQtTG9nICJSZW1v
>> "%TMP_B64%" echo dmluZyBrbm93biBDb2RleCBwYXRocy4uLiIKCiAgICAkZGlycyA9IEAoCiAgICAgICAgIiRlbnY6
>> "%TMP_B64%" echo VVNFUlBST0ZJTEVcLmNvZGV4IiwKICAgICAgICAiJGVudjpBUFBEQVRBXENvZGV4IiwKICAgICAg
>> "%TMP_B64%" echo ICAiJGVudjpBUFBEQVRBXE9wZW5BSSBDb2RleCIsCiAgICAgICAgIiRlbnY6QVBQREFUQVxPcGVu
>> "%TMP_B64%" echo QUlcQ29kZXgiLAogICAgICAgICIkZW52OkFQUERBVEFcY29tLm9wZW5haS5jb2RleCIsCiAgICAg
>> "%TMP_B64%" echo ICAgIiRlbnY6TE9DQUxBUFBEQVRBXENvZGV4IiwKICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFc
>> "%TMP_B64%" echo T3BlbkFJIENvZGV4IiwKICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFcT3BlbkFJXENvZGV4IiwK
>> "%TMP_B64%" echo ICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFcY29tLm9wZW5haS5jb2RleCIsCiAgICAgICAgIiRl
>> "%TMP_B64%" echo bnY6TE9DQUxBUFBEQVRBXFByb2dyYW1zXENvZGV4IiwKICAgICAgICAiJGVudjpMT0NBTEFQUERB
>> "%TMP_B64%" echo VEFcUHJvZ3JhbXNcT3BlbkFJIENvZGV4IiwKICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFcY29k
>> "%TMP_B64%" echo ZXgiLAogICAgICAgICIkZW52OkxPQ0FMQVBQREFUQVxUZW1wXENvZGV4IiwKICAgICAgICAiJGVu
>> "%TMP_B64%" echo djpBUFBEQVRBXG5wbVxub2RlX21vZHVsZXNcQG9wZW5haVxjb2RleCIsCiAgICAgICAgIiRlbnY6
>> "%TMP_B64%" echo UFJPR1JBTURBVEFcQ29kZXgiLAogICAgICAgICIkZW52OlBST0dSQU1EQVRBXE9wZW5BSVxDb2Rl
>> "%TMP_B64%" echo eCIsCiAgICAgICAgIiRlbnY6UHJvZ3JhbUZpbGVzXENvZGV4IiwKICAgICAgICAiJGVudjpQcm9n
>> "%TMP_B64%" echo cmFtRmlsZXNcT3BlbkFJIENvZGV4IiwKICAgICAgICAiJHtlbnY6UHJvZ3JhbUZpbGVzKHg4Nil9
>> "%TMP_B64%" echo XENvZGV4IiwKICAgICAgICAiJHtlbnY6UHJvZ3JhbUZpbGVzKHg4Nil9XE9wZW5BSSBDb2RleCIK
>> "%TMP_B64%" echo ICAgICkKCiAgICBmb3JlYWNoICgkZGlyIGluICRkaXJzKSB7CiAgICAgICAgUmVtb3ZlLUNvZGV4
>> "%TMP_B64%" echo RGlyZWN0b3J5IC1QYXRoICRkaXIKICAgIH0KCiAgICAkZmlsZXMgPSBAKAogICAgICAgICIkZW52
>> "%TMP_B64%" echo OlVTRVJQUk9GSUxFXC5jb2RleC5qc29uIiwKICAgICAgICAiJGVudjpVU0VSUFJPRklMRVwuY29k
>> "%TMP_B64%" echo ZXguanNvbi5iYWsiLAogICAgICAgICIkZW52OkFQUERBVEFcbnBtXGNvZGV4LmNtZCIsCiAgICAg
>> "%TMP_B64%" echo ICAgIiRlbnY6QVBQREFUQVxucG1cY29kZXgucHMxIiwKICAgICAgICAiJGVudjpBUFBEQVRBXG5w
>> "%TMP_B64%" echo bVxjb2RleCIsCiAgICAgICAgIiRlbnY6QVBQREFUQVxNaWNyb3NvZnRcV2luZG93c1xTdGFydCBN
>> "%TMP_B64%" echo ZW51XFByb2dyYW1zXENvZGV4LmxuayIsCiAgICAgICAgIiRlbnY6QVBQREFUQVxNaWNyb3NvZnRc
>> "%TMP_B64%" echo V2luZG93c1xTdGFydCBNZW51XFByb2dyYW1zXE9wZW5BSSBDb2RleC5sbmsiLAogICAgICAgICIk
>> "%TMP_B64%" echo ZW52OlBVQkxJQ1xEZXNrdG9wXENvZGV4LmxuayIsCiAgICAgICAgIiRlbnY6UFVCTElDXERlc2t0
>> "%TMP_B64%" echo b3BcT3BlbkFJIENvZGV4LmxuayIsCiAgICAgICAgIiRlbnY6VVNFUlBST0ZJTEVcRGVza3RvcFxD
>> "%TMP_B64%" echo b2RleC5sbmsiLAogICAgICAgICIkZW52OlVTRVJQUk9GSUxFXERlc2t0b3BcT3BlbkFJIENvZGV4
>> "%TMP_B64%" echo LmxuayIKICAgICkKCiAgICBmb3JlYWNoICgkZmlsZSBpbiAkZmlsZXMpIHsKICAgICAgICBSZW1v
>> "%TMP_B64%" echo dmUtQ29kZXhGaWxlIC1QYXRoICRmaWxlCiAgICB9Cn0KCmZ1bmN0aW9uIFJlbW92ZS1FbXB0eVBh
>> "%TMP_B64%" echo cmVudHMgewogICAgJHBhcmVudHMgPSBAKAogICAgICAgICIkZW52OkFQUERBVEFcT3BlbkFJIiwK
>> "%TMP_B64%" echo ICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFcT3BlbkFJIiwKICAgICAgICAiJGVudjpQUk9HUkFN
>> "%TMP_B64%" echo REFUQVxPcGVuQUkiCiAgICApCgogICAgZm9yZWFjaCAoJHBhcmVudCBpbiAkcGFyZW50cykgewog
>> "%TMP_B64%" echo ICAgICAgIGlmIChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRwYXJlbnQgLVBhdGhUeXBlIENvbnRh
>> "%TMP_B64%" echo aW5lcikgewogICAgICAgICAgICB0cnkgewogICAgICAgICAgICAgICAgUmVtb3ZlLUl0ZW0gLUxp
>> "%TMP_B64%" echo dGVyYWxQYXRoICRwYXJlbnQgLUZvcmNlIC1FcnJvckFjdGlvbiBTdG9wCiAgICAgICAgICAgICAg
>> "%TMP_B64%" echo ICBBZGQtTG9nICJSZW1vdmVkIGVtcHR5IGRpcmVjdG9yeTogJHBhcmVudCIKICAgICAgICAgICAg
>> "%TMP_B64%" echo fSBjYXRjaCB7CiAgICAgICAgICAgICAgICBBZGQtTG9nICJQYXJlbnQgZGlyZWN0b3J5IG5vdCBl
>> "%TMP_B64%" echo bXB0eSBvciBub3QgcmVtb3ZhYmxlOiAkcGFyZW50IgogICAgICAgICAgICB9CiAgICAgICAgfQog
>> "%TMP_B64%" echo ICAgfQp9CgpmdW5jdGlvbiBTaG93LU1lbnUgewogICAgQ2xlYXItSG9zdAogICAgV3JpdGUtSG9z
>> "%TMP_B64%" echo dCAiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09IgogICAgV3JpdGUtSG9zdCAiIENvZGV4IOyCreygnCDrj4TqtawgZm9yIFdpbmRvd3Mi
>> "%TMP_B64%" echo CiAgICBXcml0ZS1Ib3N0ICIgQ29kZXggVW5pbnN0YWxsZXIgZm9yIFdpbmRvd3MiCiAgICBXcml0
>> "%TMP_B64%" echo ZS1Ib3N0ICI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT0iCiAgICBXcml0ZS1Ib3N0ICIiCiAgICBXcml0ZS1Ib3N0ICIgMS4gQ29kZXgg
>> "%TMP_B64%" echo 7ZSE66Gc6re4656oLCDsiqTtgqwsIOyEpOyglSwg7LqQ7IucLCDrjIDtmZQg6riw66GdIOuqqOuR
>> "%TMP_B64%" echo kCDsgq3soJwiCiAgICBXcml0ZS1Ib3N0ICIgICAgUmVtb3ZlIENvZGV4IHByb2dyYW0sIHNraWxs
>> "%TMP_B64%" echo cywgc2V0dGluZ3MsIGNhY2hlLCBhbmQgY2hhdCBkYXRhIgogICAgV3JpdGUtSG9zdCAiIgogICAg
>> "%TMP_B64%" echo V3JpdGUtSG9zdCAiIDIuIOuCmOqwgOq4sCIKICAgIFdyaXRlLUhvc3QgIiAgICBFeGl0IgogICAg
>> "%TMP_B64%" echo V3JpdGUtSG9zdCAiIgp9Cgp3aGlsZSAoJHRydWUpIHsKICAgIFNob3ctTWVudQogICAgJGNob2lj
>> "%TMP_B64%" echo ZSA9IFJlYWQtSG9zdCAi7ISg7YOd7ZWY7IS47JqUIDEg65iQ64qUIDIgLyBTZWxlY3QgMSBvciAy
>> "%TMP_B64%" echo IgoKICAgIGlmICgkY2hvaWNlIC1lcSAiMiIpIHsKICAgICAgICBXcml0ZS1CaSAi67OA6rK9IOyX
>> "%TMP_B64%" echo huydtCDsooXro4ztlanri4jri6QuIiAiRXhpdGluZyB3aXRob3V0IGNoYW5nZXMuIgogICAgICAg
>> "%TMP_B64%" echo IGV4aXQgMAogICAgfQoKICAgIGlmICgkY2hvaWNlIC1uZSAiMSIpIHsKICAgICAgICBXcml0ZS1C
>> "%TMP_B64%" echo aSAi7J6Y66q765CcIOyEoO2DneyeheuLiOuLpC4gMSDrmJDripQgMuunjCDsnoXroKXtlZjshLjs
>> "%TMP_B64%" echo mpQuIiAiSW52YWxpZCBjaG9pY2UuIFBsZWFzZSB0eXBlIG9ubHkgMSBvciAyLiIKICAgICAgICBS
>> "%TMP_B64%" echo ZWFkLUhvc3QgIkVudGVyIO2CpOulvCDriITrpbTshLjsmpQgLyBQcmVzcyBFbnRlciIKICAgICAg
>> "%TMP_B64%" echo ICBjb250aW51ZQogICAgfQoKICAgIFdyaXRlLUhvc3QgIiIKICAgIFdyaXRlLUJpICJDb2RleCDq
>> "%TMP_B64%" echo tIDroKgg7YyM7J286rO8IOygle2Zle2eiCDtmZXsnbjrkJwgQ29kZXgg7ISk7LmYIO2Vreuqqeun
>> "%TMP_B64%" echo jCDsgq3soJztlanri4jri6QuIiAiVGhpcyByZW1vdmVzIG9ubHkgQ29kZXgtcmVsYXRlZCBmaWxl
>> "%TMP_B64%" echo cyBhbmQgZXhhY3QgQ29kZXggaW5zdGFsbHMuIgogICAgV3JpdGUtQmkgIuuLpOuluCBXaW5kb3dz
>> "%TMP_B64%" echo IO2UhOuhnOq3uOueqOydgCDsgq3soJwg64yA7IOB7J20IOyVhOuLmeuLiOuLpC4iICJPdGhlciBX
>> "%TMP_B64%" echo aW5kb3dzIHByb2dyYW1zIGFyZSBub3QgdGFyZ2V0ZWQuIgogICAgV3JpdGUtSG9zdCAiIgogICAg
>> "%TMP_B64%" echo JGNvbmZpcm0gPSBSZWFkLUhvc3QgIuqzhOyGje2VmOugpOuptCBERUxFVEUg7J6F66ClIC8gVHlw
>> "%TMP_B64%" echo ZSBERUxFVEUgdG8gY29udGludWUiCgogICAgaWYgKCRjb25maXJtIC1pbmUgIkRFTEVURSIpIHsK
>> "%TMP_B64%" echo ICAgICAgICBXcml0ZS1CaSAi67OA6rK9IOyXhuydtCDsooXro4ztlanri4jri6QuIiAiRXhpdGlu
>> "%TMP_B64%" echo ZyB3aXRob3V0IGNoYW5nZXMuIgogICAgICAgIGV4aXQgMAogICAgfQoKICAgIENsZWFyLUhvc3QK
>> "%TMP_B64%" echo ICAgIFdyaXRlLUJpICJDb2RleCDsgq3soJzrpbwg7Iuc7J6R7ZWp64uI64ukLi4uIiAiU3RhcnRp
>> "%TMP_B64%" echo bmcgQ29kZXggY2xlYW51cC4uLiIKICAgIFdyaXRlLUJpICLroZzqt7g6ICRMb2dGaWxlIiAiTG9n
>> "%TMP_B64%" echo OiAkTG9nRmlsZSIKICAgIEFkZC1Mb2cgIkNvZGV4IGNsZWFudXAgc3RhcnRlZCBhdCAkKEdldC1E
>> "%TMP_B64%" echo YXRlIC1Gb3JtYXQgJ3l5eXktTU0tZGQgSEg6bW06c3MnKSIKCiAgICBpZiAoVGVzdC1BZG1pbikg
>> "%TMP_B64%" echo ewogICAgICAgIEFkZC1Mb2cgIlJ1bm5pbmcgd2l0aCBhZG1pbmlzdHJhdG9yIHBlcm1pc3Npb24u
>> "%TMP_B64%" echo IgogICAgfSBlbHNlIHsKICAgICAgICBBZGQtTG9nICJSdW5uaW5nIHdpdGhvdXQgYWRtaW5pc3Ry
>> "%TMP_B64%" echo YXRvciBwZXJtaXNzaW9uLiBNYWNoaW5lLXdpZGUgaW5zdGFsbHMgbWF5IG5lZWQgUnVuIGFzIGFk
>> "%TMP_B64%" echo bWluaXN0cmF0b3IuIgogICAgICAgIFdyaXRlLUJpICLssLjqs6A6IOyghOyytCDsgqzsmqnsnpDs
>> "%TMP_B64%" echo mqkg7ISk7LmY6rmM7KeAIOyCreygnO2VmOugpOuptCAuYmF0IO2MjOydvOydhCDsmrDtgbTrpq3t
>> "%TMP_B64%" echo lZwg65KkIOq0gOumrOyekCDqtoztlZzsnLzroZwg7Iuk7ZaJ7ZWY7IS47JqULiIgIk5vdGU6IEZv
>> "%TMP_B64%" echo ciBtYWNoaW5lLXdpZGUgaW5zdGFsbHMsIHJpZ2h0LWNsaWNrIHRoZSAuYmF0IGZpbGUgYW5kIGNo
>> "%TMP_B64%" echo b29zZSBSdW4gYXMgYWRtaW5pc3RyYXRvci4iCiAgICAgICAgV3JpdGUtSG9zdCAiIgogICAgfQoK
>> "%TMP_B64%" echo ICAgIFN0b3AtQ29kZXhQcm9jZXNzZXMKICAgIFVuaW5zdGFsbC1Lbm93blBhY2thZ2VzCiAgICBS
>> "%TMP_B64%" echo ZW1vdmUtS25vd25QYXRocwogICAgUmVtb3ZlLUVtcHR5UGFyZW50cwoKICAgIEFkZC1Mb2cgIkZp
>> "%TMP_B64%" echo bmlzaGVkIGF0ICQoR2V0LURhdGUgLUZvcm1hdCAneXl5eS1NTS1kZCBISDptbTpzcycpIgogICAg
>> "%TMP_B64%" echo V3JpdGUtSG9zdCAiIgogICAgV3JpdGUtSG9zdCAiPT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09IgogICAgV3JpdGUtSG9zdCAiIOyZhOuj
>> "%TMP_B64%" echo jCAvIERvbmUiCiAgICBXcml0ZS1Ib3N0ICI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iCiAgICBXcml0ZS1Ib3N0ICIiCiAgICBXcml0
>> "%TMP_B64%" echo ZS1CaSAi66Gc6re46rCAIOyggOyepeuQmOyXiOyKteuLiOuLpDogJExvZ0ZpbGUiICJBIGxvZyB3
>> "%TMP_B64%" echo YXMgc2F2ZWQgaGVyZTogJExvZ0ZpbGUiCiAgICBleGl0IDAKfQo=
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { [IO.File]::WriteAllBytes($env:TMP_PS, [Convert]::FromBase64String((Get-Content -LiteralPath $env:TMP_B64 -Raw))); exit 0 } catch { Write-Host $_.Exception.Message; exit 1 }"
if errorlevel 1 goto fail
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%TMP_PS%"
set "EXIT_CODE=%ERRORLEVEL%"
del /f /q "%TMP_PS%" >nul 2>nul
del /f /q "%TMP_B64%" >nul 2>nul
echo.
pause
exit /b %EXIT_CODE%
:fail
echo Failed to start Codex Uninstaller.
echo Please run this file from a writable user folder, such as Downloads or Desktop.
del /f /q "%TMP_PS%" >nul 2>nul
del /f /q "%TMP_B64%" >nul 2>nul
echo.
pause
exit /b 1
