@echo off
setlocal EnableExtensions DisableDelayedExpansion
title Codex Uninstaller
rem Double-click launcher. It asks Windows for administrator permission automatically.
set "__CODEX_UNINSTALLER_ELEVATED="
if /i "%~1"=="--elevated" set "__CODEX_UNINSTALLER_ELEVATED=1"
fltmc >nul 2>nul
if errorlevel 1 (
    if defined __CODEX_UNINSTALLER_ELEVATED (
        echo Failed to start with administrator permission.
        echo Please approve the Windows administrator prompt and try again.
        echo.
        pause
        exit /b 1
    )
    set "__CODEX_UNINSTALLER_BAT=%~f0"
    powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -Command "Start-Process -FilePath $env:ComSpec -ArgumentList @('/d','/c','\"' + $env:__CODEX_UNINSTALLER_BAT + '\" --elevated') -Verb RunAs -WorkingDirectory (Get-Location).Path"
    exit /b
)
rem Single-file launcher.
rem The long Base64 lines below are the embedded PowerShell uninstaller script.
rem This keeps Korean/English UI text reliable on Windows while users download only this .bat.
rem It decodes to %TEMP%, runs, then deletes the temporary files.
set "TMP_PS=%TEMP%\codex-uninstaller-%RANDOM%%RANDOM%.ps1"
set "TMP_B64=%TEMP%\codex-uninstaller-%RANDOM%%RANDOM%.b64"
break > "%TMP_B64%"
>> "%TMP_B64%" echo 77u/JEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJDb250aW51ZSIKCmZ1bmN0aW9uIFdyaXRlLUJp
>> "%TMP_B64%" echo IHsKICAgIHBhcmFtKAogICAgICAgIFtQYXJhbWV0ZXIoTWFuZGF0b3J5ID0gJHRydWUpXVtzdHJp
>> "%TMP_B64%" echo bmddJEtvLAogICAgICAgIFtQYXJhbWV0ZXIoTWFuZGF0b3J5ID0gJHRydWUpXVtzdHJpbmddJEVu
>> "%TMP_B64%" echo CiAgICApCiAgICBXcml0ZS1Ib3N0ICRLbwogICAgV3JpdGUtSG9zdCAkRW4KfQoKZnVuY3Rpb24g
>> "%TMP_B64%" echo QWRkLUxvZyB7CiAgICBwYXJhbShbc3RyaW5nXSRNZXNzYWdlKQp9CgpmdW5jdGlvbiBUZXN0LUFk
>> "%TMP_B64%" echo bWluIHsKICAgICRpZGVudGl0eSA9IFtTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0lkZW50aXR5
>> "%TMP_B64%" echo XTo6R2V0Q3VycmVudCgpCiAgICAkcHJpbmNpcGFsID0gTmV3LU9iamVjdCBTZWN1cml0eS5Qcmlu
>> "%TMP_B64%" echo Y2lwYWwuV2luZG93c1ByaW5jaXBhbCgkaWRlbnRpdHkpCiAgICByZXR1cm4gJHByaW5jaXBhbC5J
>> "%TMP_B64%" echo c0luUm9sZShbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NCdWlsdEluUm9sZV06OkFkbWluaXN0
>> "%TMP_B64%" echo cmF0b3IpCn0NCg0KZnVuY3Rpb24gUmVzdGFydC1XaW5kb3dzU2hlbGxTZWFyY2ggewogICAgV3Jp
>> "%TMP_B64%" echo dGUtQmkgIldpbmRvd3Mg6rKA7IOJL+yLnOyekSDrqZTribTrpbwg7IOI66Gc6rOg7Lmo7ZWp64uI
>> "%TMP_B64%" echo 64ukLi4uIiAiUmVmcmVzaGluZyBXaW5kb3dzIFNlYXJjaCBhbmQgU3RhcnQgbWVudS4uLiIKICAg
>> "%TMP_B64%" echo IGZvcmVhY2ggKCRuYW1lIGluIEAoIlNlYXJjaEhvc3QiLCAiU3RhcnRNZW51RXhwZXJpZW5jZUhv
>> "%TMP_B64%" echo c3QiLCAiU2hlbGxFeHBlcmllbmNlSG9zdCIsICJleHBsb3JlciIpKSB7CiAgICAgICAgdHJ5IHsK
>> "%TMP_B64%" echo ICAgICAgICAgICAgR2V0LVByb2Nlc3MgLU5hbWUgJG5hbWUgLUVycm9yQWN0aW9uIFNpbGVudGx5
>> "%TMP_B64%" echo Q29udGludWUgfCBTdG9wLVByb2Nlc3MgLUZvcmNlIC1FcnJvckFjdGlvbiBTdG9wCiAgICAgICAg
>> "%TMP_B64%" echo ICAgIEFkZC1Mb2cgIlN0b3BwZWQgV2luZG93cyBzaGVsbC9zZWFyY2ggcHJvY2VzczogJG5hbWUi
>> "%TMP_B64%" echo CiAgICAgICAgfSBjYXRjaCB7CiAgICAgICAgICAgIEFkZC1Mb2cgIkNvdWxkIG5vdCBzdG9wIFdp
>> "%TMP_B64%" echo bmRvd3Mgc2hlbGwvc2VhcmNoIHByb2Nlc3M6ICRuYW1lIC0gJCgkXy5FeGNlcHRpb24uTWVzc2Fn
>> "%TMP_B64%" echo ZSkiCiAgICAgICAgfQogICAgfQoKICAgIHRyeSB7CiAgICAgICAgU3RhcnQtUHJvY2VzcyBleHBs
>> "%TMP_B64%" echo b3Jlci5leGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKICAgICAgICBBZGQtTG9nICJT
>> "%TMP_B64%" echo dGFydGVkIFdpbmRvd3MgRXhwbG9yZXIuIgogICAgfSBjYXRjaCB7CiAgICAgICAgQWRkLUxvZyAi
>> "%TMP_B64%" echo RmFpbGVkIHRvIHN0YXJ0IFdpbmRvd3MgRXhwbG9yZXIgLSAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdl
>> "%TMP_B64%" echo KSIKICAgIH0KfQoKZnVuY3Rpb24gVGVzdC1Db2RleFBhY2thZ2VJZGVudGl0eSB7CiAgICBwYXJh
>> "%TMP_B64%" echo bShbb2JqZWN0XSRQYWNrYWdlKQoKICAgICRuYW1lID0gW3N0cmluZ10kUGFja2FnZS5OYW1lCiAg
>> "%TMP_B64%" echo ICAkdmFsdWVzID0gQCgKICAgICAgICAkbmFtZSwKICAgICAgICBbc3RyaW5nXSRQYWNrYWdlLlBh
>> "%TMP_B64%" echo Y2thZ2VGdWxsTmFtZSwKICAgICAgICBbc3RyaW5nXSRQYWNrYWdlLlBhY2thZ2VGYW1pbHlOYW1l
>> "%TMP_B64%" echo LAogICAgICAgIFtzdHJpbmddJFBhY2thZ2UuUHVibGlzaGVyRGlzcGxheU5hbWUKICAgICkgLWpv
>> "%TMP_B64%" echo aW4gInwiCgogICAgJG5vcm1hbGl6ZWQgPSAkdmFsdWVzLlRvTG93ZXJJbnZhcmlhbnQoKQogICAg
>> "%TMP_B64%" echo cmV0dXJuICgKICAgICAgICAkbmFtZSAtaWVxICJDb2RleCIgLW9yCiAgICAgICAgJG5hbWUgLWll
>> "%TMP_B64%" echo cSAiT3BlbkFJLkNvZGV4IiAtb3IKICAgICAgICAoJG5vcm1hbGl6ZWQuQ29udGFpbnMoImNvZGV4
>> "%TMP_B64%" echo IikgLWFuZCAoCiAgICAgICAgICAgICRub3JtYWxpemVkLkNvbnRhaW5zKCJvcGVuYWkiKSAtb3IK
>> "%TMP_B64%" echo ICAgICAgICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMoImNvbS5vcGVuYWkiKSAtb3IKICAgICAg
>> "%TMP_B64%" echo ICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMoIm9wZW5haS5jb2RleCIpCiAgICAgICAgKSkKICAg
>> "%TMP_B64%" echo ICkKfQoKZnVuY3Rpb24gVW5pbnN0YWxsLUNvZGV4QXBweFBhY2thZ2VzIHsKICAgIFdyaXRlLUJp
>> "%TMP_B64%" echo ICJXaW5kb3dzIOyVseycvOuhnCDrk7HroZ3rkJwgQ29kZXjrpbwg7KCc6rGw7ZWp64uI64ukLi4u
>> "%TMP_B64%" echo IiAiUmVtb3ZpbmcgQ29kZXggcmVnaXN0ZXJlZCBhcyBhIFdpbmRvd3MgYXBwLi4uIgogICAgQWRk
>> "%TMP_B64%" echo LUxvZyAiQ2hlY2tpbmcgQXBweC9NU0lYIENvZGV4IHBhY2thZ2VzLi4uIgoKICAgICRwYWNrYWdl
>> "%TMP_B64%" echo cyA9IEAoKQogICAgdHJ5IHsKICAgICAgICAkcGFja2FnZXMgKz0gR2V0LUFwcHhQYWNrYWdlIC1O
>> "%TMP_B64%" echo YW1lICIqQ29kZXgqIiAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQogICAgICAgIGlmIChU
>> "%TMP_B64%" echo ZXN0LUFkbWluKSB7CiAgICAgICAgICAgICRwYWNrYWdlcyArPSBHZXQtQXBweFBhY2thZ2UgLUFs
>> "%TMP_B64%" echo bFVzZXJzIC1OYW1lICIqQ29kZXgqIiAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQogICAg
>> "%TMP_B64%" echo ICAgIH0KICAgIH0gY2F0Y2ggewogICAgICAgIEFkZC1Mb2cgIkZhaWxlZCB0byBxdWVyeSBBcHB4
>> "%TMP_B64%" echo IHBhY2thZ2VzIC0gJCgkXy5FeGNlcHRpb24uTWVzc2FnZSkiCiAgICB9CgogICAgJHBhY2thZ2Vz
>> "%TMP_B64%" echo IHwKICAgICAgICBXaGVyZS1PYmplY3QgeyBUZXN0LUNvZGV4UGFja2FnZUlkZW50aXR5IC1QYWNr
>> "%TMP_B64%" echo YWdlICRfIH0gfAogICAgICAgIFNvcnQtT2JqZWN0IFBhY2thZ2VGdWxsTmFtZSAtVW5pcXVlIHwK
>> "%TMP_B64%" echo ICAgICAgICBGb3JFYWNoLU9iamVjdCB7CiAgICAgICAgICAgIHRyeSB7CiAgICAgICAgICAgICAg
>> "%TMP_B64%" echo ICBXcml0ZS1CaSAiV2luZG93cyDslbEgQ29kZXgg7KCc6rGwOiAkKCRfLk5hbWUpIiAiUmVtb3Zp
>> "%TMP_B64%" echo bmcgV2luZG93cyBhcHAgcGFja2FnZTogJCgkXy5OYW1lKSIKICAgICAgICAgICAgICAgIGlmIChU
>> "%TMP_B64%" echo ZXN0LUFkbWluKSB7CiAgICAgICAgICAgICAgICAgICAgUmVtb3ZlLUFwcHhQYWNrYWdlIC1QYWNr
>> "%TMP_B64%" echo YWdlICRfLlBhY2thZ2VGdWxsTmFtZSAtQWxsVXNlcnMgLUVycm9yQWN0aW9uIFN0b3AKICAgICAg
>> "%TMP_B64%" echo ICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICAgICAgUmVtb3ZlLUFwcHhQYWNrYWdl
>> "%TMP_B64%" echo IC1QYWNrYWdlICRfLlBhY2thZ2VGdWxsTmFtZSAtRXJyb3JBY3Rpb24gU3RvcAogICAgICAgICAg
>> "%TMP_B64%" echo ICAgICAgfQogICAgICAgICAgICAgICAgQWRkLUxvZyAiUmVtb3ZlZCBBcHB4IHBhY2thZ2U6ICQo
>> "%TMP_B64%" echo JF8uUGFja2FnZUZ1bGxOYW1lKSIKICAgICAgICAgICAgfSBjYXRjaCB7CiAgICAgICAgICAgICAg
>> "%TMP_B64%" echo ICBBZGQtTG9nICJGYWlsZWQgdG8gcmVtb3ZlIEFwcHggcGFja2FnZTogJCgkXy5QYWNrYWdlRnVs
>> "%TMP_B64%" echo bE5hbWUpIC0gJCgkXy5FeGNlcHRpb24uTWVzc2FnZSkiCiAgICAgICAgICAgICAgICB0cnkgewog
>> "%TMP_B64%" echo ICAgICAgICAgICAgICAgICAgIFJlbW92ZS1BcHB4UGFja2FnZSAtUGFja2FnZSAkXy5QYWNrYWdl
>> "%TMP_B64%" echo RnVsbE5hbWUgLUVycm9yQWN0aW9uIFN0b3AKICAgICAgICAgICAgICAgICAgICBBZGQtTG9nICJS
>> "%TMP_B64%" echo ZW1vdmVkIEFwcHggcGFja2FnZSBmb3IgY3VycmVudCB1c2VyOiAkKCRfLlBhY2thZ2VGdWxsTmFt
>> "%TMP_B64%" echo ZSkiCiAgICAgICAgICAgICAgICB9IGNhdGNoIHsKICAgICAgICAgICAgICAgICAgICBXcml0ZS1C
>> "%TMP_B64%" echo aSAiV2luZG93cyDslbEgQ29kZXgg7KCc6rGwIOyLpO2MqDogJCgkXy5OYW1lKSIgIkZhaWxlZCB0
>> "%TMP_B64%" echo byByZW1vdmUgV2luZG93cyBhcHAgcGFja2FnZTogJCgkXy5OYW1lKSIKICAgICAgICAgICAgICAg
>> "%TMP_B64%" echo ICAgICBBZGQtTG9nICJGYWxsYmFjayBBcHB4IHJlbW92YWwgZmFpbGVkOiAkKCRfLlBhY2thZ2VG
>> "%TMP_B64%" echo dWxsTmFtZSkgLSAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdlKSIKICAgICAgICAgICAgICAgIH0KICAg
>> "%TMP_B64%" echo ICAgICAgICAgfQogICAgICAgIH0KCiAgICBpZiAoVGVzdC1BZG1pbikgewogICAgICAgIHRyeSB7
>> "%TMP_B64%" echo CiAgICAgICAgICAgIEdldC1BcHB4UHJvdmlzaW9uZWRQYWNrYWdlIC1PbmxpbmUgLUVycm9yQWN0
>> "%TMP_B64%" echo aW9uIFNpbGVudGx5Q29udGludWUgfAogICAgICAgICAgICAgICAgV2hlcmUtT2JqZWN0IHsKICAg
>> "%TMP_B64%" echo ICAgICAgICAgICAgICAgICAkaWRlbnRpdHkgPSAiJCgkXy5EaXNwbGF5TmFtZSl8JCgkXy5QYWNr
>> "%TMP_B64%" echo YWdlTmFtZSkiLlRvTG93ZXJJbnZhcmlhbnQoKQogICAgICAgICAgICAgICAgICAgICRpZGVudGl0
>> "%TMP_B64%" echo eS5Db250YWlucygiY29kZXgiKSAtYW5kICRpZGVudGl0eS5Db250YWlucygib3BlbmFpIikKICAg
>> "%TMP_B64%" echo ICAgICAgICAgICAgIH0gfAogICAgICAgICAgICAgICAgRm9yRWFjaC1PYmplY3QgewogICAgICAg
>> "%TMP_B64%" echo ICAgICAgICAgICAgIHRyeSB7CiAgICAgICAgICAgICAgICAgICAgICAgIFdyaXRlLUJpICLsgqzs
>> "%TMP_B64%" echo oIQg7ISk7LmY65CcIENvZGV4IOyVsSDtjKjtgqTsp4Ag7KCc6rGwOiAkKCRfLkRpc3BsYXlOYW1l
>> "%TMP_B64%" echo KSIgIlJlbW92aW5nIHByb3Zpc2lvbmVkIENvZGV4IGFwcCBwYWNrYWdlOiAkKCRfLkRpc3BsYXlO
>> "%TMP_B64%" echo YW1lKSIKICAgICAgICAgICAgICAgICAgICAgICAgUmVtb3ZlLUFwcHhQcm92aXNpb25lZFBhY2th
>> "%TMP_B64%" echo Z2UgLU9ubGluZSAtUGFja2FnZU5hbWUgJF8uUGFja2FnZU5hbWUgLUVycm9yQWN0aW9uIFN0b3Ag
>> "%TMP_B64%" echo Kj4gJG51bGwKICAgICAgICAgICAgICAgICAgICAgICAgQWRkLUxvZyAiUmVtb3ZlZCBwcm92aXNp
>> "%TMP_B64%" echo b25lZCBBcHB4IHBhY2thZ2U6ICQoJF8uUGFja2FnZU5hbWUpIgogICAgICAgICAgICAgICAgICAg
>> "%TMP_B64%" echo IH0gY2F0Y2ggewogICAgICAgICAgICAgICAgICAgICAgICBBZGQtTG9nICJGYWlsZWQgdG8gcmVt
>> "%TMP_B64%" echo b3ZlIHByb3Zpc2lvbmVkIHBhY2thZ2U6ICQoJF8uUGFja2FnZU5hbWUpIC0gJCgkXy5FeGNlcHRp
>> "%TMP_B64%" echo b24uTWVzc2FnZSkiCiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAg
>> "%TMP_B64%" echo ICAgIH0gY2F0Y2ggewogICAgICAgICAgICBBZGQtTG9nICJGYWlsZWQgdG8gcXVlcnkgcHJvdmlz
>> "%TMP_B64%" echo aW9uZWQgQXBweCBwYWNrYWdlcyAtICQoJF8uRXhjZXB0aW9uLk1lc3NhZ2UpIgogICAgICAgIH0K
>> "%TMP_B64%" echo ICAgIH0KfQoKZnVuY3Rpb24gVGVzdC1Db2RleFRhcmdldCB7CiAgICBwYXJhbShbc3RyaW5nXSRQ
>> "%TMP_B64%" echo YXRoKQogICAgaWYgKFtzdHJpbmddOjpJc051bGxPcldoaXRlU3BhY2UoJFBhdGgpKSB7CiAgICAg
>> "%TMP_B64%" echo ICAgcmV0dXJuICRmYWxzZQogICAgfQoKICAgICRub3JtYWxpemVkID0gJFBhdGguVG9Mb3dlcklu
>> "%TMP_B64%" echo dmFyaWFudCgpCiAgICByZXR1cm4gKAogICAgICAgICRub3JtYWxpemVkLkNvbnRhaW5zKCJcLmNv
>> "%TMP_B64%" echo ZGV4IikgLW9yCiAgICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMoIlxjb2RleCIpIC1vcgogICAg
>> "%TMP_B64%" echo ICAgICRub3JtYWxpemVkLkNvbnRhaW5zKCJjb2RleC4iKSAtb3IKICAgICAgICAkbm9ybWFsaXpl
>> "%TMP_B64%" echo ZC5Db250YWlucygiY29kZXgubG5rIikgLW9yCiAgICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMo
>> "%TMP_B64%" echo Im9wZW5haSBjb2RleCIpIC1vcgogICAgICAgICRub3JtYWxpemVkLkNvbnRhaW5zKCJcb3BlbmFp
>> "%TMP_B64%" echo XGNvZGV4IikgLW9yCiAgICAgICAgJG5vcm1hbGl6ZWQuQ29udGFpbnMoImNvbS5vcGVuYWkuY29k
>> "%TMP_B64%" echo ZXgiKSAtb3IKICAgICAgICAkbm9ybWFsaXplZC5Db250YWlucygiXEBvcGVuYWlcY29kZXgiKQog
>> "%TMP_B64%" echo ICAgKQp9CgpmdW5jdGlvbiBSZW1vdmUtQ29kZXhEaXJlY3RvcnkgewogICAgcGFyYW0oW3N0cmlu
>> "%TMP_B64%" echo Z10kUGF0aCkKICAgIGlmIChbc3RyaW5nXTo6SXNOdWxsT3JXaGl0ZVNwYWNlKCRQYXRoKSAtb3Ig
>> "%TMP_B64%" echo LW5vdCAoVGVzdC1QYXRoIC1MaXRlcmFsUGF0aCAkUGF0aCAtUGF0aFR5cGUgQ29udGFpbmVyKSkg
>> "%TMP_B64%" echo ewogICAgICAgIHJldHVybgogICAgfQoKICAgIGlmICgtbm90IChUZXN0LUNvZGV4VGFyZ2V0IC1Q
>> "%TMP_B64%" echo YXRoICRQYXRoKSkgewogICAgICAgIFdyaXRlLUJpICLslYjsoIQg67KU7JyEIOuwluydtOudvCDq
>> "%TMP_B64%" echo sbTrhIjrnIA6ICRQYXRoIiAiU2tpcHBlZCB1bnNhZmUgZGlyZWN0b3J5OiAkUGF0aCIKICAgICAg
>> "%TMP_B64%" echo ICBBZGQtTG9nICJTa2lwcGVkIHVuc2FmZSBkaXJlY3Rvcnk6ICRQYXRoIgogICAgICAgIHJldHVy
>> "%TMP_B64%" echo bgogICAgfQoKICAgIHRyeSB7CiAgICAgICAgUmVtb3ZlLUl0ZW0gLUxpdGVyYWxQYXRoICRQYXRo
>> "%TMP_B64%" echo IC1SZWN1cnNlIC1Gb3JjZSAtRXJyb3JBY3Rpb24gU3RvcAogICAgICAgIFdyaXRlLUJpICLtj7Tr
>> "%TMP_B64%" echo jZQg7IKt7KCcIOyZhOujjDogJFBhdGgiICJSZW1vdmVkIGRpcmVjdG9yeTogJFBhdGgiCiAgICAg
>> "%TMP_B64%" echo ICAgQWRkLUxvZyAiUmVtb3ZlZCBkaXJlY3Rvcnk6ICRQYXRoIgogICAgfSBjYXRjaCB7CiAgICAg
>> "%TMP_B64%" echo ICAgV3JpdGUtQmkgIu2PtOuNlCDsgq3soJwg7Iuk7YyoOiAkUGF0aCIgIkZhaWxlZCB0byByZW1v
>> "%TMP_B64%" echo dmUgZGlyZWN0b3J5OiAkUGF0aCIKICAgICAgICBBZGQtTG9nICJGYWlsZWQgdG8gcmVtb3ZlIGRp
>> "%TMP_B64%" echo cmVjdG9yeTogJFBhdGggLSAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdlKSIKICAgIH0KfQoKZnVuY3Rp
>> "%TMP_B64%" echo b24gUmVtb3ZlLUNvZGV4RmlsZSB7CiAgICBwYXJhbShbc3RyaW5nXSRQYXRoKQogICAgaWYgKFtz
>> "%TMP_B64%" echo dHJpbmddOjpJc051bGxPcldoaXRlU3BhY2UoJFBhdGgpIC1vciAtbm90IChUZXN0LVBhdGggLUxp
>> "%TMP_B64%" echo dGVyYWxQYXRoICRQYXRoIC1QYXRoVHlwZSBMZWFmKSkgewogICAgICAgIHJldHVybgogICAgfQoK
>> "%TMP_B64%" echo ICAgIGlmICgtbm90IChUZXN0LUNvZGV4VGFyZ2V0IC1QYXRoICRQYXRoKSkgewogICAgICAgIFdy
>> "%TMP_B64%" echo aXRlLUJpICLslYjsoIQg67KU7JyEIOuwluydtOudvCDqsbTrhIjrnIA6ICRQYXRoIiAiU2tpcHBl
>> "%TMP_B64%" echo ZCB1bnNhZmUgZmlsZTogJFBhdGgiCiAgICAgICAgQWRkLUxvZyAiU2tpcHBlZCB1bnNhZmUgZmls
>> "%TMP_B64%" echo ZTogJFBhdGgiCiAgICAgICAgcmV0dXJuCiAgICB9CgogICAgdHJ5IHsKICAgICAgICBSZW1vdmUt
>> "%TMP_B64%" echo SXRlbSAtTGl0ZXJhbFBhdGggJFBhdGggLUZvcmNlIC1FcnJvckFjdGlvbiBTdG9wCiAgICAgICAg
>> "%TMP_B64%" echo V3JpdGUtQmkgIu2MjOydvCDsgq3soJwg7JmE66OMOiAkUGF0aCIgIlJlbW92ZWQgZmlsZTogJFBh
>> "%TMP_B64%" echo dGgiCiAgICAgICAgQWRkLUxvZyAiUmVtb3ZlZCBmaWxlOiAkUGF0aCIKICAgIH0gY2F0Y2ggewog
>> "%TMP_B64%" echo ICAgICAgIFdyaXRlLUJpICLtjIzsnbwg7IKt7KCcIOyLpO2MqDogJFBhdGgiICJGYWlsZWQgdG8g
>> "%TMP_B64%" echo cmVtb3ZlIGZpbGU6ICRQYXRoIgogICAgICAgIEFkZC1Mb2cgIkZhaWxlZCB0byByZW1vdmUgZmls
>> "%TMP_B64%" echo ZTogJFBhdGggLSAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdlKSIKICAgIH0KfQoKZnVuY3Rpb24gU3Rv
>> "%TMP_B64%" echo cC1Db2RleFByb2Nlc3NlcyB7CiAgICBXcml0ZS1CaSAi7Iuk7ZaJIOykkeyduCBDb2RleOulvCDs
>> "%TMP_B64%" echo ooXro4ztlanri4jri6QuLi4iICJDbG9zaW5nIENvZGV4IGlmIGl0IGlzIHJ1bm5pbmcuLi4iCiAg
>> "%TMP_B64%" echo ICBBZGQtTG9nICJDbG9zaW5nIENvZGV4IHByb2Nlc3Nlcy4uLiIKCiAgICAkcHJvY2Vzc05hbWVz
>> "%TMP_B64%" echo ID0gQCgiQ29kZXgiLCAiT3BlbkFJIENvZGV4IiwgImNvZGV4IikKICAgIGZvcmVhY2ggKCRuYW1l
>> "%TMP_B64%" echo IGluICRwcm9jZXNzTmFtZXMpIHsKICAgICAgICBHZXQtUHJvY2VzcyAtTmFtZSAkbmFtZSAtRXJy
>> "%TMP_B64%" echo b3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSB8IEZvckVhY2gtT2JqZWN0IHsKICAgICAgICAgICAg
>> "%TMP_B64%" echo dHJ5IHsKICAgICAgICAgICAgICAgIFN0b3AtUHJvY2VzcyAtSWQgJF8uSWQgLUZvcmNlIC1FcnJv
>> "%TMP_B64%" echo ckFjdGlvbiBTdG9wCiAgICAgICAgICAgICAgICBBZGQtTG9nICJTdG9wcGVkIHByb2Nlc3M6ICQo
>> "%TMP_B64%" echo JF8uUHJvY2Vzc05hbWUpIFskKCRfLklkKV0iCiAgICAgICAgICAgIH0gY2F0Y2ggewogICAgICAg
>> "%TMP_B64%" echo ICAgICAgICAgQWRkLUxvZyAiRmFpbGVkIHRvIHN0b3AgcHJvY2VzczogJCgkXy5Qcm9jZXNzTmFt
>> "%TMP_B64%" echo ZSkgWyQoJF8uSWQpXSAtICQoJF8uRXhjZXB0aW9uLk1lc3NhZ2UpIgogICAgICAgICAgICB9CiAg
>> "%TMP_B64%" echo ICAgICAgfQogICAgfQp9CgpmdW5jdGlvbiBVbmluc3RhbGwtS25vd25QYWNrYWdlcyB7CiAgICBX
>> "%TMP_B64%" echo cml0ZS1CaSAi7JWM66Ck7KeEIENvZGV4IO2MqO2CpOyngCDshKTsuZgg7ZWt66qp7J2EIO2Zleyd
>> "%TMP_B64%" echo uO2VqeuLiOuLpC4uLiIgIkNoZWNraW5nIGtub3duIENvZGV4IHBhY2thZ2UgaW5zdGFsbGVycy4u
>> "%TMP_B64%" echo LiIKICAgIEFkZC1Mb2cgIkNoZWNraW5nIHBhY2thZ2UgaW5zdGFsbGVycy4uLiIKCiAgICBpZiAo
>> "%TMP_B64%" echo R2V0LUNvbW1hbmQgd2luZ2V0IC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSB7CiAgICAg
>> "%TMP_B64%" echo ICAgJHdpbmdldElkcyA9IEAoIk9wZW5BSS5Db2RleCIsICJPcGVuQUkuQ29kZXhDTEkiLCAiQ29k
>> "%TMP_B64%" echo ZXguQ29kZXgiKQogICAgICAgIGZvcmVhY2ggKCRpZCBpbiAkd2luZ2V0SWRzKSB7CiAgICAgICAg
>> "%TMP_B64%" echo ICAgIEFkZC1Mb2cgIndpbmdldCB1bmluc3RhbGwgLS1pZCAkaWQgLS1leGFjdCIKICAgICAgICAg
>> "%TMP_B64%" echo ICAgJiB3aW5nZXQgdW5pbnN0YWxsIC0taWQgJGlkIC0tZXhhY3QgLS1zaWxlbnQgLS1hY2NlcHQt
>> "%TMP_B64%" echo c291cmNlLWFncmVlbWVudHMgLS1kaXNhYmxlLWludGVyYWN0aXZpdHkgKj4gJG51bGwKICAgICAg
>> "%TMP_B64%" echo ICB9CiAgICB9CgogICAgaWYgKEdldC1Db21tYW5kIG5wbSAtRXJyb3JBY3Rpb24gU2lsZW50bHlD
>> "%TMP_B64%" echo b250aW51ZSkgewogICAgICAgIEFkZC1Mb2cgIm5wbSB1bmluc3RhbGwgLWcgQG9wZW5haS9jb2Rl
>> "%TMP_B64%" echo eCIKICAgICAgICAmIG5wbSB1bmluc3RhbGwgLWcgIkBvcGVuYWkvY29kZXgiICo+ICRudWxsCiAg
>> "%TMP_B64%" echo ICB9Cn0KCmZ1bmN0aW9uIEludm9rZS1Db2RleFVuaW5zdGFsbGVyRmlsZSB7CiAgICBwYXJhbSgK
>> "%TMP_B64%" echo ICAgICAgICBbc3RyaW5nXSRQYXRoLAogICAgICAgIFtzdHJpbmdbXV0kQXJndW1lbnRzID0gQCgp
>> "%TMP_B64%" echo CiAgICApCgogICAgaWYgKFtzdHJpbmddOjpJc051bGxPcldoaXRlU3BhY2UoJFBhdGgpIC1vciAt
>> "%TMP_B64%" echo bm90IChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRQYXRoIC1QYXRoVHlwZSBMZWFmKSkgewogICAg
>> "%TMP_B64%" echo ICAgIHJldHVybgogICAgfQoKICAgIGlmICgtbm90IChUZXN0LUNvZGV4VGFyZ2V0IC1QYXRoICRQ
>> "%TMP_B64%" echo YXRoKSkgewogICAgICAgIFdyaXRlLUJpICLslYjsoIQg67KU7JyEIOuwluydtOudvCDqsbTrhIjr
>> "%TMP_B64%" echo nIA6ICRQYXRoIiAiU2tpcHBlZCB1bnNhZmUgdW5pbnN0YWxsZXI6ICRQYXRoIgogICAgICAgIHJl
>> "%TMP_B64%" echo dHVybgogICAgfQoKICAgIHRyeSB7CiAgICAgICAgV3JpdGUtQmkgIkNvZGV4IOygnOqxsCDtlITr
>> "%TMP_B64%" echo oZzqt7jrnqgg7Iuk7ZaJOiAkUGF0aCIgIlJ1bm5pbmcgQ29kZXggdW5pbnN0YWxsZXI6ICRQYXRo
>> "%TMP_B64%" echo IgogICAgICAgICRwcm9jZXNzID0gU3RhcnQtUHJvY2VzcyAtRmlsZVBhdGggJFBhdGggLUFyZ3Vt
>> "%TMP_B64%" echo ZW50TGlzdCAkQXJndW1lbnRzIC1XYWl0IC1QYXNzVGhydSAtV2luZG93U3R5bGUgSGlkZGVuIC1F
>> "%TMP_B64%" echo cnJvckFjdGlvbiBTdG9wCiAgICAgICAgQWRkLUxvZyAiVW5pbnN0YWxsZXIgZXhpdGVkIHdpdGgg
>> "%TMP_B64%" echo Y29kZSAkKCRwcm9jZXNzLkV4aXRDb2RlKTogJFBhdGgiCiAgICB9IGNhdGNoIHsKICAgICAgICBX
>> "%TMP_B64%" echo cml0ZS1CaSAiQ29kZXgg7KCc6rGwIO2UhOuhnOq3uOueqCDsi6Ttlokg7Iuk7YyoOiAkUGF0aCIg
>> "%TMP_B64%" echo IkZhaWxlZCB0byBydW4gQ29kZXggdW5pbnN0YWxsZXI6ICRQYXRoIgogICAgICAgIEFkZC1Mb2cg
>> "%TMP_B64%" echo IkZhaWxlZCB0byBydW4gdW5pbnN0YWxsZXI6ICRQYXRoIC0gJCgkXy5FeGNlcHRpb24uTWVzc2Fn
>> "%TMP_B64%" echo ZSkiCiAgICB9Cn0KCmZ1bmN0aW9uIEludm9rZS1Db2RleFJlZ2lzdHJ5VW5pbnN0YWxsIHsKICAg
>> "%TMP_B64%" echo IHBhcmFtKFtvYmplY3RdJEVudHJ5KQoKICAgICRkaXNwbGF5TmFtZSA9IFtzdHJpbmddJEVudHJ5
>> "%TMP_B64%" echo LkRpc3BsYXlOYW1lCiAgICAkY29tbWFuZCA9IFtzdHJpbmddJEVudHJ5LlF1aWV0VW5pbnN0YWxs
>> "%TMP_B64%" echo U3RyaW5nCiAgICBpZiAoW3N0cmluZ106OklzTnVsbE9yV2hpdGVTcGFjZSgkY29tbWFuZCkpIHsK
>> "%TMP_B64%" echo ICAgICAgICAkY29tbWFuZCA9IFtzdHJpbmddJEVudHJ5LlVuaW5zdGFsbFN0cmluZwogICAgfQoK
>> "%TMP_B64%" echo ICAgIGlmICgkZGlzcGxheU5hbWUgLW5vdGluIEAoIkNvZGV4IiwgIk9wZW5BSSBDb2RleCIpIC1v
>> "%TMP_B64%" echo ciBbc3RyaW5nXTo6SXNOdWxsT3JXaGl0ZVNwYWNlKCRjb21tYW5kKSkgewogICAgICAgIHJldHVy
>> "%TMP_B64%" echo bgogICAgfQoKICAgIHRyeSB7CiAgICAgICAgV3JpdGUtQmkgIuuTseuhneuQnCBDb2RleCDtlITr
>> "%TMP_B64%" echo oZzqt7jrnqgg7KCc6rGwOiAkZGlzcGxheU5hbWUiICJVbmluc3RhbGxpbmcgcmVnaXN0ZXJlZCBD
>> "%TMP_B64%" echo b2RleCBhcHA6ICRkaXNwbGF5TmFtZSIKICAgICAgICAkcHJvY2VzcyA9IFN0YXJ0LVByb2Nlc3Mg
>> "%TMP_B64%" echo LUZpbGVQYXRoICJjbWQuZXhlIiAtQXJndW1lbnRMaXN0IEAoIi9kIiwgIi9zIiwgIi9jIiwgJGNv
>> "%TMP_B64%" echo bW1hbmQpIC1XYWl0IC1QYXNzVGhydSAtV2luZG93U3R5bGUgSGlkZGVuIC1FcnJvckFjdGlvbiBT
>> "%TMP_B64%" echo dG9wCiAgICAgICAgQWRkLUxvZyAiUmVnaXN0cnkgdW5pbnN0YWxsZXIgZXhpdGVkIHdpdGggY29k
>> "%TMP_B64%" echo ZSAkKCRwcm9jZXNzLkV4aXRDb2RlKTogJGRpc3BsYXlOYW1lIgogICAgfSBjYXRjaCB7CiAgICAg
>> "%TMP_B64%" echo ICAgV3JpdGUtQmkgIuuTseuhneuQnCBDb2RleCDtlITroZzqt7jrnqgg7KCc6rGwIOyLpO2MqDog
>> "%TMP_B64%" echo JGRpc3BsYXlOYW1lIiAiRmFpbGVkIHRvIHVuaW5zdGFsbCByZWdpc3RlcmVkIENvZGV4IGFwcDog
>> "%TMP_B64%" echo JGRpc3BsYXlOYW1lIgogICAgICAgIEFkZC1Mb2cgIkZhaWxlZCByZWdpc3RyeSB1bmluc3RhbGw6
>> "%TMP_B64%" echo ICRkaXNwbGF5TmFtZSAtICQoJF8uRXhjZXB0aW9uLk1lc3NhZ2UpIgogICAgfQp9CgpmdW5jdGlv
>> "%TMP_B64%" echo biBVbmluc3RhbGwtQ29kZXhBcHBsaWNhdGlvbnMgewogICAgV3JpdGUtQmkgIkNvZGV4IO2UhOuh
>> "%TMP_B64%" echo nOq3uOueqCDsoJzqsbAg7ZWt66qp7J2EIOyLpO2Wie2VqeuLiOuLpC4uLiIgIlJ1bm5pbmcgQ29k
>> "%TMP_B64%" echo ZXggYXBwbGljYXRpb24gdW5pbnN0YWxsZXJzLi4uIgoKICAgICR1bmluc3RhbGxLZXlzID0gQCgK
>> "%TMP_B64%" echo ICAgICAgICAiSEtDVTpcU29mdHdhcmVcTWljcm9zb2Z0XFdpbmRvd3NcQ3VycmVudFZlcnNpb25c
>> "%TMP_B64%" echo VW5pbnN0YWxsXCoiLAogICAgICAgICJIS0xNOlxTb2Z0d2FyZVxNaWNyb3NvZnRcV2luZG93c1xD
>> "%TMP_B64%" echo dXJyZW50VmVyc2lvblxVbmluc3RhbGxcKiIsCiAgICAgICAgIkhLTE06XFNvZnR3YXJlXFdPVzY0
>> "%TMP_B64%" echo MzJOb2RlXE1pY3Jvc29mdFxXaW5kb3dzXEN1cnJlbnRWZXJzaW9uXFVuaW5zdGFsbFwqIgogICAg
>> "%TMP_B64%" echo KQoKICAgIGZvcmVhY2ggKCRrZXkgaW4gJHVuaW5zdGFsbEtleXMpIHsKICAgICAgICBHZXQtSXRl
>> "%TMP_B64%" echo bVByb3BlcnR5IC1QYXRoICRrZXkgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfAogICAg
>> "%TMP_B64%" echo ICAgICAgICBXaGVyZS1PYmplY3QgeyAkXy5EaXNwbGF5TmFtZSAtaW4gQCgiQ29kZXgiLCAiT3Bl
>> "%TMP_B64%" echo bkFJIENvZGV4IikgfSB8CiAgICAgICAgICAgIEZvckVhY2gtT2JqZWN0IHsgSW52b2tlLUNvZGV4
>> "%TMP_B64%" echo UmVnaXN0cnlVbmluc3RhbGwgLUVudHJ5ICRfIH0KICAgIH0KCiAgICAka25vd25Vbmluc3RhbGxl
>> "%TMP_B64%" echo cnMgPSBAKAogICAgICAgIEB7IFBhdGggPSAiJGVudjpMT0NBTEFQUERBVEFcUHJvZ3JhbXNcQ29k
>> "%TMP_B64%" echo ZXhcVW5pbnN0YWxsIENvZGV4LmV4ZSI7IEFyZ3MgPSBAKCIvUyIpIH0sCiAgICAgICAgQHsgUGF0
>> "%TMP_B64%" echo aCA9ICIkZW52OkxPQ0FMQVBQREFUQVxQcm9ncmFtc1xPcGVuQUkgQ29kZXhcVW5pbnN0YWxsIE9w
>> "%TMP_B64%" echo ZW5BSSBDb2RleC5leGUiOyBBcmdzID0gQCgiL1MiKSB9LAogICAgICAgIEB7IFBhdGggPSAiJGVu
>> "%TMP_B64%" echo djpMT0NBTEFQUERBVEFcUHJvZ3JhbXNcQ29kZXhcVXBkYXRlLmV4ZSI7IEFyZ3MgPSBAKCItLXVu
>> "%TMP_B64%" echo aW5zdGFsbCIsICItcyIpIH0sCiAgICAgICAgQHsgUGF0aCA9ICIkZW52OkxPQ0FMQVBQREFUQVxQ
>> "%TMP_B64%" echo cm9ncmFtc1xPcGVuQUkgQ29kZXhcVXBkYXRlLmV4ZSI7IEFyZ3MgPSBAKCItLXVuaW5zdGFsbCIs
>> "%TMP_B64%" echo ICItcyIpIH0sCiAgICAgICAgQHsgUGF0aCA9ICIkZW52OlByb2dyYW1GaWxlc1xDb2RleFxVbmlu
>> "%TMP_B64%" echo c3RhbGwgQ29kZXguZXhlIjsgQXJncyA9IEAoIi9TIikgfSwKICAgICAgICBAeyBQYXRoID0gIiRl
>> "%TMP_B64%" echo bnY6UHJvZ3JhbUZpbGVzXE9wZW5BSSBDb2RleFxVbmluc3RhbGwgT3BlbkFJIENvZGV4LmV4ZSI7
>> "%TMP_B64%" echo IEFyZ3MgPSBAKCIvUyIpIH0sCiAgICAgICAgQHsgUGF0aCA9ICIke2VudjpQcm9ncmFtRmlsZXMo
>> "%TMP_B64%" echo eDg2KX1cQ29kZXhcVW5pbnN0YWxsIENvZGV4LmV4ZSI7IEFyZ3MgPSBAKCIvUyIpIH0sCiAgICAg
>> "%TMP_B64%" echo ICAgQHsgUGF0aCA9ICIke2VudjpQcm9ncmFtRmlsZXMoeDg2KX1cT3BlbkFJIENvZGV4XFVuaW5z
>> "%TMP_B64%" echo dGFsbCBPcGVuQUkgQ29kZXguZXhlIjsgQXJncyA9IEAoIi9TIikgfQogICAgKQoKICAgIGZvcmVh
>> "%TMP_B64%" echo Y2ggKCRpdGVtIGluICRrbm93blVuaW5zdGFsbGVycykgewogICAgICAgIEludm9rZS1Db2RleFVu
>> "%TMP_B64%" echo aW5zdGFsbGVyRmlsZSAtUGF0aCAkaXRlbS5QYXRoIC1Bcmd1bWVudHMgJGl0ZW0uQXJncwogICAg
>> "%TMP_B64%" echo fQp9CgpmdW5jdGlvbiBSZW1vdmUtS25vd25QYXRocyB7CiAgICBXcml0ZS1CaSAiQ29kZXgg7YyM
>> "%TMP_B64%" echo 7J28LCDsiqTtgqwsIOyEpOyglSwg7LqQ7IucLCDrjIDtmZQg6riw66Gd7J2EIOyCreygnO2VqeuL
>> "%TMP_B64%" echo iOuLpC4uLiIgIlJlbW92aW5nIENvZGV4IGZpbGVzLCBza2lsbHMsIHNldHRpbmdzLCBjYWNoZSwg
>> "%TMP_B64%" echo YW5kIGNoYXQgZGF0YS4uLiIKICAgIEFkZC1Mb2cgIlJlbW92aW5nIGtub3duIENvZGV4IHBhdGhz
>> "%TMP_B64%" echo Li4uIgoKICAgICRkaXJzID0gQCgKICAgICAgICAiJGVudjpVU0VSUFJPRklMRVwuY29kZXgiLAog
>> "%TMP_B64%" echo ICAgICAgICIkZW52OkFQUERBVEFcQ29kZXgiLAogICAgICAgICIkZW52OkFQUERBVEFcT3BlbkFJ
>> "%TMP_B64%" echo IENvZGV4IiwKICAgICAgICAiJGVudjpBUFBEQVRBXE9wZW5BSVxDb2RleCIsCiAgICAgICAgIiRl
>> "%TMP_B64%" echo bnY6QVBQREFUQVxjb20ub3BlbmFpLmNvZGV4IiwKICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFc
>> "%TMP_B64%" echo Q29kZXgiLAogICAgICAgICIkZW52OkxPQ0FMQVBQREFUQVxPcGVuQUkgQ29kZXgiLAogICAgICAg
>> "%TMP_B64%" echo ICIkZW52OkxPQ0FMQVBQREFUQVxPcGVuQUlcQ29kZXgiLAogICAgICAgICIkZW52OkxPQ0FMQVBQ
>> "%TMP_B64%" echo REFUQVxjb20ub3BlbmFpLmNvZGV4IiwKICAgICAgICAiJGVudjpMT0NBTEFQUERBVEFcUHJvZ3Jh
>> "%TMP_B64%" echo bXNcQ29kZXgiLAogICAgICAgICIkZW52OkxPQ0FMQVBQREFUQVxQcm9ncmFtc1xPcGVuQUkgQ29k
>> "%TMP_B64%" echo ZXgiLAogICAgICAgICIkZW52OkxPQ0FMQVBQREFUQVxjb2RleCIsCiAgICAgICAgIiRlbnY6TE9D
>> "%TMP_B64%" echo QUxBUFBEQVRBXFRlbXBcQ29kZXgiLAogICAgICAgICIkZW52OkFQUERBVEFcbnBtXG5vZGVfbW9k
>> "%TMP_B64%" echo dWxlc1xAb3BlbmFpXGNvZGV4IiwKICAgICAgICAiJGVudjpQUk9HUkFNREFUQVxDb2RleCIsCiAg
>> "%TMP_B64%" echo ICAgICAgIiRlbnY6UFJPR1JBTURBVEFcT3BlbkFJXENvZGV4IiwKICAgICAgICAiJGVudjpQcm9n
>> "%TMP_B64%" echo cmFtRmlsZXNcQ29kZXgiLAogICAgICAgICIkZW52OlByb2dyYW1GaWxlc1xPcGVuQUkgQ29kZXgi
>> "%TMP_B64%" echo LAogICAgICAgICIke2VudjpQcm9ncmFtRmlsZXMoeDg2KX1cQ29kZXgiLAogICAgICAgICIke2Vu
>> "%TMP_B64%" echo djpQcm9ncmFtRmlsZXMoeDg2KX1cT3BlbkFJIENvZGV4IgogICAgKQoKICAgIGZvcmVhY2ggKCRk
>> "%TMP_B64%" echo aXIgaW4gJGRpcnMpIHsKICAgICAgICBSZW1vdmUtQ29kZXhEaXJlY3RvcnkgLVBhdGggJGRpcgog
>> "%TMP_B64%" echo ICAgfQoKICAgICRmaWxlcyA9IEAoCiAgICAgICAgIiRlbnY6VVNFUlBST0ZJTEVcLmNvZGV4Lmpz
>> "%TMP_B64%" echo b24iLAogICAgICAgICIkZW52OlVTRVJQUk9GSUxFXC5jb2RleC5qc29uLmJhayIsCiAgICAgICAg
>> "%TMP_B64%" echo IiRlbnY6QVBQREFUQVxucG1cY29kZXguY21kIiwKICAgICAgICAiJGVudjpBUFBEQVRBXG5wbVxj
>> "%TMP_B64%" echo b2RleC5wczEiLAogICAgICAgICIkZW52OkFQUERBVEFcbnBtXGNvZGV4IiwKICAgICAgICAiJGVu
>> "%TMP_B64%" echo djpBUFBEQVRBXE1pY3Jvc29mdFxXaW5kb3dzXFN0YXJ0IE1lbnVcUHJvZ3JhbXNcQ29kZXgubG5r
>> "%TMP_B64%" echo IiwKICAgICAgICAiJGVudjpBUFBEQVRBXE1pY3Jvc29mdFxXaW5kb3dzXFN0YXJ0IE1lbnVcUHJv
>> "%TMP_B64%" echo Z3JhbXNcT3BlbkFJIENvZGV4LmxuayIsCiAgICAgICAgIiRlbnY6UFVCTElDXERlc2t0b3BcQ29k
>> "%TMP_B64%" echo ZXgubG5rIiwKICAgICAgICAiJGVudjpQVUJMSUNcRGVza3RvcFxPcGVuQUkgQ29kZXgubG5rIiwK
>> "%TMP_B64%" echo ICAgICAgICAiJGVudjpVU0VSUFJPRklMRVxEZXNrdG9wXENvZGV4LmxuayIsCiAgICAgICAgIiRl
>> "%TMP_B64%" echo bnY6VVNFUlBST0ZJTEVcRGVza3RvcFxPcGVuQUkgQ29kZXgubG5rIgogICAgKQoKICAgIGZvcmVh
>> "%TMP_B64%" echo Y2ggKCRmaWxlIGluICRmaWxlcykgewogICAgICAgIFJlbW92ZS1Db2RleEZpbGUgLVBhdGggJGZp
>> "%TMP_B64%" echo bGUKICAgIH0KfQoKZnVuY3Rpb24gUmVtb3ZlLUVtcHR5UGFyZW50cyB7CiAgICAkcGFyZW50cyA9
>> "%TMP_B64%" echo IEAoCiAgICAgICAgIiRlbnY6QVBQREFUQVxPcGVuQUkiLAogICAgICAgICIkZW52OkxPQ0FMQVBQ
>> "%TMP_B64%" echo REFUQVxPcGVuQUkiLAogICAgICAgICIkZW52OlBST0dSQU1EQVRBXE9wZW5BSSIKICAgICkKCiAg
>> "%TMP_B64%" echo ICBmb3JlYWNoICgkcGFyZW50IGluICRwYXJlbnRzKSB7CiAgICAgICAgaWYgKFRlc3QtUGF0aCAt
>> "%TMP_B64%" echo TGl0ZXJhbFBhdGggJHBhcmVudCAtUGF0aFR5cGUgQ29udGFpbmVyKSB7CiAgICAgICAgICAgIHRy
>> "%TMP_B64%" echo eSB7CiAgICAgICAgICAgICAgICBSZW1vdmUtSXRlbSAtTGl0ZXJhbFBhdGggJHBhcmVudCAtRm9y
>> "%TMP_B64%" echo Y2UgLUVycm9yQWN0aW9uIFN0b3AKICAgICAgICAgICAgICAgIEFkZC1Mb2cgIlJlbW92ZWQgZW1w
>> "%TMP_B64%" echo dHkgZGlyZWN0b3J5OiAkcGFyZW50IgogICAgICAgICAgICB9IGNhdGNoIHsKICAgICAgICAgICAg
>> "%TMP_B64%" echo ICAgIEFkZC1Mb2cgIlBhcmVudCBkaXJlY3Rvcnkgbm90IGVtcHR5IG9yIG5vdCByZW1vdmFibGU6
>> "%TMP_B64%" echo ICRwYXJlbnQiCiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cn0KCmZ1bmN0aW9uIFNob3ct
>> "%TMP_B64%" echo TWVudSB7CiAgICBDbGVhci1Ib3N0CiAgICBXcml0ZS1Ib3N0ICI9PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iCiAgICBXcml0ZS1Ib3N0
>> "%TMP_B64%" echo ICIgQ29kZXgg7IKt7KCcIOuPhOq1rCBmb3IgV2luZG93cyIKICAgIFdyaXRlLUhvc3QgIiBDb2Rl
>> "%TMP_B64%" echo eCBVbmluc3RhbGxlciBmb3IgV2luZG93cyIKICAgIFdyaXRlLUhvc3QgIj09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIKICAgIFdyaXRl
>> "%TMP_B64%" echo LUhvc3QgIiIKICAgIFdyaXRlLUhvc3QgIiAxLiBDb2RleCDtlITroZzqt7jrnqgsIOyKpO2CrCwg
>> "%TMP_B64%" echo 7ISk7KCVLCDsupDsi5wsIOuMgO2ZlCDquLDroZ0g66qo65GQIOyCreygnCIKICAgIFdyaXRlLUhv
>> "%TMP_B64%" echo c3QgIiAgICBSZW1vdmUgQ29kZXggcHJvZ3JhbSwgc2tpbGxzLCBzZXR0aW5ncywgY2FjaGUsIGFu
>> "%TMP_B64%" echo ZCBjaGF0IGRhdGEiCiAgICBXcml0ZS1Ib3N0ICIiCiAgICBXcml0ZS1Ib3N0ICIgMi4g64KY6rCA
>> "%TMP_B64%" echo 6riwIgogICAgV3JpdGUtSG9zdCAiICAgIEV4aXQiCiAgICBXcml0ZS1Ib3N0ICIiCn0KCndoaWxl
>> "%TMP_B64%" echo ICgkdHJ1ZSkgewogICAgU2hvdy1NZW51CiAgICAkY2hvaWNlID0gUmVhZC1Ib3N0ICLshKDtg53t
>> "%TMP_B64%" echo lZjshLjsmpQgMSDrmJDripQgMiAvIFNlbGVjdCAxIG9yIDIiCgogICAgaWYgKCRjaG9pY2UgLWVx
>> "%TMP_B64%" echo ICIyIikgewogICAgICAgIFdyaXRlLUJpICLrs4Dqsr0g7JeG7J20IOyiheujjO2VqeuLiOuLpC4i
>> "%TMP_B64%" echo ICJFeGl0aW5nIHdpdGhvdXQgY2hhbmdlcy4iCiAgICAgICAgZXhpdCAwCiAgICB9CgogICAgaWYg
>> "%TMP_B64%" echo KCRjaG9pY2UgLW5lICIxIikgewogICAgICAgIFdyaXRlLUJpICLsnpjrqrvrkJwg7ISg7YOd7J6F
>> "%TMP_B64%" echo 64uI64ukLiAxIOuYkOuKlCAy66eMIOyeheugpe2VmOyEuOyalC4iICJJbnZhbGlkIGNob2ljZS4g
>> "%TMP_B64%" echo UGxlYXNlIHR5cGUgb25seSAxIG9yIDIuIgogICAgICAgIFJlYWQtSG9zdCAiRW50ZXIg7YKk66W8
>> "%TMP_B64%" echo IOuIhOultOyEuOyalCAvIFByZXNzIEVudGVyIgogICAgICAgIGNvbnRpbnVlCiAgICB9CgogICAg
>> "%TMP_B64%" echo V3JpdGUtSG9zdCAiIgogICAgV3JpdGUtQmkgIkNvZGV4IOq0gOugqCDtjIzsnbzqs7wg7KCV7ZmV
>> "%TMP_B64%" echo 7Z6IIO2ZleyduOuQnCBDb2RleCDshKTsuZgg7ZWt66qp66eMIOyCreygnO2VqeuLiOuLpC4iICJU
>> "%TMP_B64%" echo aGlzIHJlbW92ZXMgb25seSBDb2RleC1yZWxhdGVkIGZpbGVzIGFuZCBleGFjdCBDb2RleCBpbnN0
>> "%TMP_B64%" echo YWxscy4iCiAgICBXcml0ZS1CaSAi64uk66W4IFdpbmRvd3Mg7ZSE66Gc6re4656o7J2AIOyCreyg
>> "%TMP_B64%" echo nCDrjIDsg4HsnbQg7JWE64uZ64uI64ukLiIgIk90aGVyIFdpbmRvd3MgcHJvZ3JhbXMgYXJlIG5v
>> "%TMP_B64%" echo dCB0YXJnZXRlZC4iCiAgICBXcml0ZS1Ib3N0ICIiCiAgICAkY29uZmlybSA9IFJlYWQtSG9zdCAi
>> "%TMP_B64%" echo 6rOE7IaN7ZWY66Ck66m0IERFTEVURSDsnoXroKUgLyBUeXBlIERFTEVURSB0byBjb250aW51ZSIK
>> "%TMP_B64%" echo CiAgICBpZiAoJGNvbmZpcm0gLWluZSAiREVMRVRFIikgewogICAgICAgIFdyaXRlLUJpICLrs4Dq
>> "%TMP_B64%" echo sr0g7JeG7J20IOyiheujjO2VqeuLiOuLpC4iICJFeGl0aW5nIHdpdGhvdXQgY2hhbmdlcy4iCiAg
>> "%TMP_B64%" echo ICAgICAgZXhpdCAwCiAgICB9CgogICAgQ2xlYXItSG9zdAogICAgV3JpdGUtQmkgIkNvZGV4IOyC
>> "%TMP_B64%" echo reygnOulvCDsi5zsnpHtlanri4jri6QuLi4iICJTdGFydGluZyBDb2RleCBjbGVhbnVwLi4uIgog
>> "%TMP_B64%" echo ICAgQWRkLUxvZyAiQ29kZXggY2xlYW51cCBzdGFydGVkIGF0ICQoR2V0LURhdGUgLUZvcm1hdCAn
>> "%TMP_B64%" echo eXl5eS1NTS1kZCBISDptbTpzcycpIgoKICAgIGlmIChUZXN0LUFkbWluKSB7CiAgICAgICAgQWRk
>> "%TMP_B64%" echo LUxvZyAiUnVubmluZyB3aXRoIGFkbWluaXN0cmF0b3IgcGVybWlzc2lvbi4iCiAgICB9IGVsc2Ug
>> "%TMP_B64%" echo ewogICAgICAgIEFkZC1Mb2cgIlJ1bm5pbmcgd2l0aG91dCBhZG1pbmlzdHJhdG9yIHBlcm1pc3Np
>> "%TMP_B64%" echo b24uIg0KICAgIH0KCiAgICBTdG9wLUNvZGV4UHJvY2Vzc2VzDQogICAgVW5pbnN0YWxsLUNvZGV4
>> "%TMP_B64%" echo QXBweFBhY2thZ2VzDQogICAgVW5pbnN0YWxsLUNvZGV4QXBwbGljYXRpb25zCiAgICBVbmluc3Rh
>> "%TMP_B64%" echo bGwtS25vd25QYWNrYWdlcwogICAgUmVtb3ZlLUtub3duUGF0aHMKICAgIFJlbW92ZS1FbXB0eVBh
>> "%TMP_B64%" echo cmVudHMNCiAgICBSZXN0YXJ0LVdpbmRvd3NTaGVsbFNlYXJjaA0KCiAgICBBZGQtTG9nICJGaW5p
>> "%TMP_B64%" echo c2hlZCBhdCAkKEdldC1EYXRlIC1Gb3JtYXQgJ3l5eXktTU0tZGQgSEg6bW06c3MnKSIKICAgIFdy
>> "%TMP_B64%" echo aXRlLUhvc3QgIiIKICAgIFdyaXRlLUhvc3QgIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIKICAgIFdyaXRlLUhvc3QgIiDsmYTro4wg
>> "%TMP_B64%" echo LyBEb25lIgogICAgV3JpdGUtSG9zdCAiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%TMP_B64%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09IgogICAgV3JpdGUtSG9zdCAiIgogICAgZXhpdCAw
>> "%TMP_B64%" echo Cn0K
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { [IO.File]::WriteAllBytes($env:TMP_PS, [Convert]::FromBase64String((Get-Content -LiteralPath $env:TMP_B64 -Raw))); exit 0 } catch { Write-Host $_.Exception.Message; exit 1 }"
if errorlevel 1 goto fail
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%TMP_PS%"
set "EXIT_CODE=%ERRORLEVEL%"
del /f /q "%TMP_PS%" >nul 2>nul
del /f /q "%TMP_B64%" >nul 2>nul
echo.
pause
exit /b %EXIT_CODE%
:fail
echo Failed to start Codex Uninstaller.
echo Please run this file from a writable user folder, such as Downloads or Desktop.
del /f /q "%TMP_PS%" >nul 2>nul
del /f /q "%TMP_B64%" >nul 2>nul
echo.
pause
exit /b 1
